CREATE TABLE IF NOT EXISTS `#__realestatenow_country` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`description` TEXT NOT NULL,
	`image` VARCHAR(70) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`name` VARCHAR(100) NOT NULL DEFAULT '',
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_state` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`countryid` INT(11) NOT NULL DEFAULT 0,
	`description` TEXT NOT NULL,
	`image` VARCHAR(70) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`),
	KEY `idx_countryid` (`countryid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_city` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`description` TEXT NOT NULL,
	`image` VARCHAR(70) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`stateid` INT(11) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`),
	KEY `idx_stateid` (`stateid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_agency` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`cityid` INT(11) NOT NULL DEFAULT 0,
	`countryid` INT(11) NOT NULL DEFAULT 0,
	`default_agency_yn` TINYINT(1) NOT NULL DEFAULT 0,
	`description` TEXT NOT NULL,
	`email` VARCHAR(255) NOT NULL DEFAULT '',
	`fax` CHAR(64) NOT NULL DEFAULT '',
	`featured` TINYINT(1) NOT NULL DEFAULT 0,
	`image` VARCHAR(70) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`license` VARCHAR(100) NOT NULL DEFAULT '',
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`phone` CHAR(64) NOT NULL DEFAULT '',
	`postcode` VARCHAR(15) NOT NULL DEFAULT '',
	`rets_source` CHAR(50) NOT NULL DEFAULT '',
	`settings_id` INT(11) NOT NULL DEFAULT 0,
	`stateid` INT(11) NOT NULL DEFAULT 0,
	`street` VARCHAR(255) NOT NULL DEFAULT '',
	`streettwo` VARCHAR(255) NOT NULL DEFAULT '',
	`website` VARCHAR(255) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_cityid` (`cityid`),
	KEY `idx_stateid` (`stateid`),
	KEY `idx_alias` (`alias`),
	KEY `idx_rets_source` (`rets_source`),
	KEY `idx_countryid` (`countryid`),
	KEY `idx_default_agency_yn` (`default_agency_yn`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_agent` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`agencyid` INT(11) NOT NULL DEFAULT 0,
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`bio` MEDIUMTEXT NOT NULL,
	`blog` VARCHAR(255) NOT NULL DEFAULT '',
	`catid` INT(11) NOT NULL DEFAULT 0,
	`cityid` INT(11) NOT NULL DEFAULT 0,
	`countryid` INT(11) NOT NULL DEFAULT 0,
	`default_agent_yn` TINYINT(1) NOT NULL DEFAULT 0,
	`email` VARCHAR(255) NOT NULL DEFAULT '',
	`fax` CHAR(64) NOT NULL DEFAULT '',
	`fbook` VARCHAR(50) NOT NULL DEFAULT '',
	`featured` TINYINT(1) NOT NULL DEFAULT 0,
	`gplus` VARCHAR(50) NOT NULL DEFAULT '',
	`image` VARCHAR(70) NOT NULL DEFAULT '',
	`instagram` VARCHAR(50) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`linkedin` VARCHAR(50) NOT NULL DEFAULT '',
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`mobile` CHAR(64) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`phone` CHAR(64) NOT NULL DEFAULT '',
	`pinterest` VARCHAR(50) NOT NULL DEFAULT '',
	`postcode` VARCHAR(15) NOT NULL DEFAULT '',
	`rets_source` CHAR(50) NOT NULL DEFAULT '',
	`settings_id` INT(11) NOT NULL DEFAULT 0,
	`skype` VARCHAR(50) NOT NULL DEFAULT '',
	`stateid` INT(11) NOT NULL DEFAULT 0,
	`street` VARCHAR(255) NOT NULL DEFAULT '',
	`streettwo` VARCHAR(255) NOT NULL DEFAULT '',
	`twitter` VARCHAR(50) NOT NULL DEFAULT '',
	`uid` INT(11) NOT NULL DEFAULT 0,
	`viewad` TINYINT(1) NOT NULL DEFAULT 1,
	`website` VARCHAR(255) NOT NULL DEFAULT '',
	`youtube` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_cityid` (`cityid`),
	KEY `idx_stateid` (`stateid`),
	KEY `idx_catid` (`catid`),
	KEY `idx_agencyid` (`agencyid`),
	KEY `idx_rets_source` (`rets_source`),
	KEY `idx_alias` (`alias`),
	KEY `idx_countryid` (`countryid`),
	KEY `idx_default_agent_yn` (`default_agent_yn`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_property` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`acrestotal` VARCHAR(20) NOT NULL DEFAULT '',
	`agent` INT(11) NOT NULL DEFAULT 0,
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`bathrooms` TINYINT(3) NOT NULL DEFAULT 0,
	`bedrooms` TINYINT(3) NOT NULL DEFAULT 0,
	`catid` INT(7) NOT NULL DEFAULT 0,
	`cityid` INT(11) NOT NULL DEFAULT 0,
	`closedate` VARCHAR(25) NOT NULL DEFAULT '',
	`closeprice` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`colistagent` INT(11) NOT NULL DEFAULT 0,
	`countryid` INT(11) NOT NULL DEFAULT 0,
	`county` VARCHAR(50) NOT NULL DEFAULT '',
	`covenantsyn` TINYINT(1) NOT NULL DEFAULT 0,
	`fbposted` CHAR(1) NOT NULL DEFAULT 0,
	`featured` TINYINT(1) NOT NULL DEFAULT 0,
	`flplone` VARCHAR(50) NOT NULL DEFAULT '',
	`flpltwo` VARCHAR(50) NOT NULL DEFAULT '',
	`fullbaths` TINYINT(3) NOT NULL DEFAULT 0,
	`ghost` TINYINT(3) NOT NULL DEFAULT 0,
	`halfbaths` TINYINT(3) NOT NULL DEFAULT 0,
	`landareasqft` VARCHAR(20) NOT NULL DEFAULT '',
	`latitude` VARCHAR(20) NOT NULL DEFAULT '',
	`listoffice` INT(11) NOT NULL DEFAULT 0,
	`longitude` VARCHAR(20) NOT NULL DEFAULT '',
	`lotdimensions` VARCHAR(20) NOT NULL DEFAULT '',
	`mediatype` TINYINT(1) NOT NULL DEFAULT 0,
	`mediaurl` VARCHAR(1024) NOT NULL DEFAULT '',
	`mkt_stats` INT(11) NOT NULL DEFAULT 0,
	`mls_id` VARCHAR(30) NOT NULL DEFAULT '',
	`mlslookup` INT(11) NOT NULL DEFAULT 0,
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`openhouse` TINYINT(1) NOT NULL DEFAULT 0,
	`openhouseinfo` TEXT NOT NULL,
	`owncoords` TINYINT(1) NOT NULL DEFAULT 0,
	`pdfinfoone` VARCHAR(50) NOT NULL DEFAULT '',
	`pdfinfotwo` VARCHAR(50) NOT NULL DEFAULT '',
	`postcode` VARCHAR(15) NOT NULL DEFAULT '',
	`price` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`priceview` VARCHAR(100) NOT NULL DEFAULT '',
	`propdesc` MEDIUMTEXT NOT NULL,
	`qtrbaths` TINYINT(3) NOT NULL DEFAULT 0,
	`rets_source` CHAR(50) NOT NULL DEFAULT '',
	`settings_id` INT(11) NOT NULL DEFAULT 0,
	`showprice` TINYINT(1) NOT NULL DEFAULT 0,
	`sold` INT(1) NOT NULL DEFAULT 0,
	`soleagency` TINYINT(1) NOT NULL DEFAULT 0,
	`sqftlower` VARCHAR(8) NOT NULL DEFAULT '',
	`sqftmainlevel` VARCHAR(8) NOT NULL DEFAULT '',
	`sqftupper` VARCHAR(8) NOT NULL DEFAULT '',
	`squarefeet` VARCHAR(50) NOT NULL DEFAULT '',
	`stateid` INT(11) NOT NULL DEFAULT 0,
	`street` VARCHAR(255) NOT NULL DEFAULT '',
	`streettwo` VARCHAR(255) NOT NULL DEFAULT '',
	`style` TEXT NOT NULL,
	`thqtrbaths` TINYINT(3) NOT NULL DEFAULT 0,
	`trans_type` INT(11) NOT NULL DEFAULT 0,
	`viewad` TINYINT(1) NOT NULL DEFAULT 1,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_cityid` (`cityid`),
	KEY `idx_stateid` (`stateid`),
	KEY `idx_catid` (`catid`),
	KEY `idx_colistagent` (`colistagent`),
	KEY `idx_agent` (`agent`),
	KEY `idx_listoffice` (`listoffice`),
	KEY `idx_rets_source` (`rets_source`),
	KEY `idx_mlslookup` (`mlslookup`),
	KEY `idx_trans_type` (`trans_type`),
	KEY `idx_mkt_stats` (`mkt_stats`),
	KEY `idx_countryid` (`countryid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_residential` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`addcustom` TEXT NOT NULL,
	`basementpctfinished` VARCHAR(50) NOT NULL DEFAULT '',
	`basementsize` VARCHAR(50) NOT NULL DEFAULT '',
	`customone` VARCHAR(150) NOT NULL DEFAULT '',
	`customthree` VARCHAR(150) NOT NULL DEFAULT '',
	`customtwo` VARCHAR(150) NOT NULL DEFAULT '',
	`ensuite` TINYINT(1) NOT NULL DEFAULT 0,
	`familyroompresent` TINYINT(1) NOT NULL DEFAULT 0,
	`flooring` VARCHAR(30) NOT NULL DEFAULT '',
	`garbagedisposalyn` TINYINT(1) NOT NULL DEFAULT 0,
	`houseconstruction` VARCHAR(30) NOT NULL DEFAULT '',
	`kitchenpresent` TINYINT(1) NOT NULL DEFAULT 0,
	`laundryroompresent` TINYINT(1) NOT NULL DEFAULT 0,
	`livingarea` VARCHAR(30) NOT NULL DEFAULT '',
	`livingroompresent` TINYINT(1) NOT NULL DEFAULT 0,
	`otherrooms` VARCHAR(50) NOT NULL DEFAULT '',
	`phoneavailableyn` TINYINT(1) NOT NULL DEFAULT 0,
	`propid` INT(11) NOT NULL DEFAULT 0,
	`storage` VARCHAR(50) NOT NULL DEFAULT '',
	`stories` TINYINT(3) NOT NULL DEFAULT 0,
	`subdivision` VARCHAR(50) NOT NULL DEFAULT '',
	`totalrooms` VARCHAR(5) NOT NULL DEFAULT '',
	`waterfront` TINYINT(1) NOT NULL DEFAULT 0,
	`waterfronttype` VARCHAR(30) NOT NULL DEFAULT '',
	`welldepth` VARCHAR(30) NOT NULL DEFAULT '',
	`year` VARCHAR(4) NOT NULL DEFAULT '',
	`yearremodeled` VARCHAR(4) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_land` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`cropping` VARCHAR(50) NOT NULL DEFAULT '',
	`fittings` VARCHAR(50) NOT NULL DEFAULT '',
	`fixtures` VARCHAR(50) NOT NULL DEFAULT '',
	`grazing` VARCHAR(50) NOT NULL DEFAULT '',
	`irrigation` VARCHAR(50) NOT NULL DEFAULT '',
	`landtype` VARCHAR(50) NOT NULL DEFAULT '',
	`propid` INT(11) NOT NULL DEFAULT 0,
	`rainfall` VARCHAR(50) NOT NULL DEFAULT '',
	`soiltype` VARCHAR(50) NOT NULL DEFAULT '',
	`stock` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_commercial` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`bldg_name` VARCHAR(50) NOT NULL DEFAULT '',
	`bussubtype` VARCHAR(30) NOT NULL DEFAULT '',
	`bustype` VARCHAR(30) NOT NULL DEFAULT '',
	`carryingcap` VARCHAR(50) NOT NULL DEFAULT '',
	`currentuse` VARCHAR(50) NOT NULL DEFAULT '',
	`loadingfac` VARCHAR(50) NOT NULL DEFAULT '',
	`netprofit` VARCHAR(30) NOT NULL DEFAULT '',
	`percentoffice` VARCHAR(50) NOT NULL DEFAULT '',
	`percentwarehouse` VARCHAR(50) NOT NULL DEFAULT '',
	`propid` INT(11) NOT NULL DEFAULT 0,
	`returns` VARCHAR(30) NOT NULL DEFAULT '',
	`takings` VARCHAR(30) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_multifamily` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`bldgsqft` VARCHAR(8) NOT NULL DEFAULT '',
	`commonareas` TEXT NOT NULL,
	`numunits` VARCHAR(7) NOT NULL DEFAULT '',
	`propid` INT(11) NOT NULL DEFAULT 0,
	`tenancytype` VARCHAR(64) NOT NULL DEFAULT '',
	`tenantpdutilities` TEXT NOT NULL,
	`totalrents` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`unitdetails` TEXT NOT NULL,
	`unitfeatures` TEXT NOT NULL,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_area` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`ctown` VARCHAR(150) NOT NULL DEFAULT '',
	`ctport` VARCHAR(150) NOT NULL DEFAULT '',
	`elementary` VARCHAR(60) NOT NULL DEFAULT '',
	`highschool` VARCHAR(60) NOT NULL DEFAULT '',
	`midschool` VARCHAR(60) NOT NULL DEFAULT '',
	`propid` INT(11) NOT NULL DEFAULT 0,
	`schooldist` VARCHAR(60) NOT NULL DEFAULT '',
	`university` VARCHAR(60) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_feature` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`appliances` TEXT NOT NULL,
	`basementandfoundation` TEXT NOT NULL,
	`buildingfeatures` TEXT NOT NULL,
	`communityfeatures` TEXT NOT NULL,
	`cooling` TEXT NOT NULL,
	`exteriorfinish` TEXT NOT NULL,
	`fencing` TEXT NOT NULL,
	`frontage` TEXT NOT NULL,
	`garagetype` TEXT NOT NULL,
	`heating` TEXT NOT NULL,
	`indoorfeatures` TEXT NOT NULL,
	`otherfeatures` TEXT NOT NULL,
	`outdoorfeatures` TEXT NOT NULL,
	`parkingdesc` VARCHAR(50) NOT NULL DEFAULT '',
	`parkingspaces` CHAR(3) NOT NULL DEFAULT '',
	`parkingspaceyn` TINYINT(1) NOT NULL DEFAULT 0,
	`porchpatio` TEXT NOT NULL,
	`propid` INT(11) NOT NULL DEFAULT 0,
	`roof` TEXT NOT NULL,
	`sewer` TEXT NOT NULL,
	`waterresources` TEXT NOT NULL,
	`zoning` TEXT NOT NULL,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_financial` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`annualinsurance` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`availdate` VARCHAR(25) NOT NULL DEFAULT '',
	`averageutilelec` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`averageutilgas` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`electricservice` VARCHAR(30) NOT NULL DEFAULT '',
	`hofees` VARCHAR(10) NOT NULL DEFAULT '',
	`pm_price_override` CHAR(1) NOT NULL DEFAULT 0,
	`pmenddate` VARCHAR(25) NOT NULL DEFAULT '',
	`pmstartdate` VARCHAR(25) NOT NULL DEFAULT '',
	`private` TEXT NOT NULL,
	`propid` INT(11) NOT NULL DEFAULT 0,
	`propmgt_description` VARCHAR(255) NOT NULL DEFAULT '',
	`propmgt_price` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`taxannual` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`taxyear` VARCHAR(4) NOT NULL DEFAULT '',
	`terms` TEXT NOT NULL,
	`utilities` TEXT NOT NULL,
	`viewbooking` TINYINT(1) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_rental` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`deposit` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`freq` INT(11) NOT NULL DEFAULT 0,
	`offpeak` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`propid` INT(11) NOT NULL DEFAULT 0,
	`rent_type` INT(11) NOT NULL DEFAULT 0,
	`sleeps` TINYINT(3) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	UNIQUE KEY `idx_propid` (`propid`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_freq` (`freq`),
	KEY `idx_rent_type` (`rent_type`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_market_status` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_transaction_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_rental_frequency` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_rent_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_feature_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`featurename` VARCHAR(255) NOT NULL DEFAULT '',
	`featuretype` TINYINT(3) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_featurename` (`featurename`),
	KEY `idx_featuretype` (`featuretype`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_mls` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`mls_disclaimer` TEXT NOT NULL,
	`mls_image` VARCHAR(255) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`),
	KEY `idx_alias` (`alias`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_favorite_listing` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`propertyid` INT(11) NOT NULL DEFAULT 0,
	`uid` INT(11) NOT NULL DEFAULT 0,
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_propertyid` (`propertyid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__realestatenow_image` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`description` TEXT NOT NULL,
	`filename` VARCHAR(255) NOT NULL DEFAULT '',
	`path` VARCHAR(255) NOT NULL DEFAULT '',
	`propid` INT(11) NOT NULL DEFAULT 0,
	`remote` CHAR(1) NOT NULL DEFAULT 0,
	`rets_source` CHAR(50) NOT NULL DEFAULT '',
	`settings_id` INT(11) NOT NULL DEFAULT 0,
	`title` CHAR(64) NOT NULL DEFAULT '',
	`type` VARCHAR(5) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_rets_source` (`rets_source`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

ALTER TABLE #__realestatenow_area CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_agent CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_commercial CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_feature CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_financial CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_land CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_multifamily CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_property CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_rental CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_residential CHANGE COLUMN access access tinyint DEFAULT 1;
ALTER TABLE #__realestatenow_property CHANGE COLUMN modified modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;



--
-- Always insure this column rules is large enough for all the access control values.
--
ALTER TABLE `#__assets` CHANGE `rules` `rules` MEDIUMTEXT NOT NULL COMMENT 'JSON encoded access control.';

--
-- Always insure this column name is large enough for long component and view names.
--
ALTER TABLE `#__assets` CHANGE `name` `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The unique name for the asset.';
